### PR TITLE
Changed the styling of the internship page

### PR DESCRIPTION
**Pull request by ayush-848**

### CODE REVIEW

**Comment by CSEdgeOff** [comment]
@ayush-848 Provide a Screenshot of the change in Desktop mode and mobile view and laptop view.

**Comment by ayush-848** [comment]
image


image


from the top

**Comment by CSEdgeOff** [comment]
@ayush-848 you worked on wrong page i think you've raised issue that you'll solve that on home page but you're showing the o/p of internships.html which is not inuse actually. 

recommit the same thing change the UI in main home page.

**Comment by ayush-848** [comment]
@CSEdgeOff Oh ok

**Comment by ayush-848** [comment]
@CSEdgeOff please check now

**Comment by CSEdgeOff** [comment]
@ayush-848 Kindly share the output so that I'll proceed.

**Comment by ayush-848** [comment]
image


image

**Pull request merged**
