### PR TITLE
Added How to create user info  based Resume maker

### LINKED ISSUE #523: [Technical Writing] : How To create a user info based Resume maker
### Description

Gathers  users professional details  And generates

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Related Issue
Added How to create user info  based Resume maker

## Description
Added How to create user info  based Resume maker

closes #523 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff @Durgesh-Vaigandla Please Review it soon

**Comment by CSEdgeOff** [comment]
@Saipradyumnagoud Missing code references in the article

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud Missing code references in the article

Yes i will add

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff @Durgesh-Vaigandla You can please Review it now

**Review by CSEdgeOff — APPROVED** [review]

**Pull request merged**
