### PR TITLE
adding colors to the website related to website's color palette

### PR DESCRIPTION
**Pull request by IshaSaini11**
## Fixes issue #89 

This enhances the UI of the website and makes it more user friendly and attractive to use and go through.

[Changes.pdf](https://github.com/CSEdgeOfficial/learn.csedge.courses/files/15286057/Changes.pdf)

### CODE REVIEW

**Comment by CSEdgeOff** [comment]
@IshaSaini11 Is it Looking good and awesome.? I'm can't able to judge that by seeing the images in the PDF I'm requesting a Video on it in different views.

**Comment by IshaSaini11** [comment]
Sure, here are the videos.

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/87354071/18cccef9-0ed4-4e7f-8f67-4734e2d1fa4e

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/87354071/8d215667-3b56-4fec-8539-6b1b2270c81b

**Comment by CSEdgeOff** [comment]
@IshaSaini11 Thanks for sharing the videos we have problem with the pink color change that into something fit there.

**Comment by IshaSaini11** [comment]
do we need to change this in both the pages shown in the video?

**Comment by CSEdgeOff** [comment]
@IshaSaini11 It Doesn't seems to be fit and the Complete UI was fixing soon so this PR is Discarding

**Pull request closed without merging**
