### PR TITLE
Create autocomment-pr-merge.yml

### LINKED ISSUE #225: [Feature] Auto Commenting feature for PR Merged
### Description

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Screenshots

PR merged

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Asymtode712**
## Related Issue
Fixes #225 

## Description
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Durgesh-Vaigandla — APPROVED** [review]

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla can you please add 'gssoc' and the relevant level labels

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 Getting some Issue could you solve that.?

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla what is it?

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 

image

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla ok so this is happening because GITHUB_TOKEN doen't have enough permissions, to correct it you must create a PAT (Personnal Access Token) and assign it to a new environment secret which can be named as PAT_GITHUB and then replace the instances of GITHUB_TOKEN with PAT_GITHUB int this code

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla this can be done by the owner only as it is caused from your environment

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 I tried that but didn't worked out could send me some reference article or video

**Comment by Asymtode712** [comment]
Firstly check this:

1. Navigate to Your Repository:

- Go to the GitHub website and navigate to the repository where you want to check the settings.

2. Access Repository Settings:

- Click on the Settings tab in your repository. This is typically found on the right side of the repository page under the repository name.

3. Go to Actions Settings:

- In the left sidebar, scroll down until you find the Actions section and click on it.

4. Check Actions Permissions:

- In the Actions settings, you will see the Actions permissions section. Ensure that Allow all actions and reusable workflows is selected. If there are restrictions, you might need to adjust them to allow the necessary actions for your workflow.

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla Ensure this :

allow workflow

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 that option is not enabled for me the repo is in organisation not in a personal account

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla please ask the owner to enable it as it's the major breaking point

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 I'm one of the super Admin I've full rights to control all the things but the wasn't enabled

**Comment by Asymtode712** [comment]
so have to enabled it now?

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 But how.!

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla Bro!!!!! By default it is set to 'Read repository contents and packages permissions' you have to change it to 'Read and write permissions'

**Comment by Asymtode712** [comment]
> Firstly check this:
> 
> 1. Navigate to Your Repository:
> 
> * Go to the GitHub website and navigate to the repository where you want to check the settings.
> 
> 2. Access Repository Settings:
> 
> * Click on the Settings tab in your repository. This is typically found on the right side of the repository page under the repository name.
> 
> 3. Go to Actions Settings:
> 
> * In the left sidebar, scroll down until you find the Actions section and click on it.
> 
> 4. Check Actions Permissions:
> 
> * In the Actions settings, you will see the Actions permissions section. Ensure that Allow all actions and reusable workflows is selected. If there are restrictions, you might need to adjust them to allow the necessary actions for your workflow.

when you follow this steps till the 3rd step just scroll down and you will find this option

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 I've already know that man but the option was not 🚫 enabling. Showing like this 🚫

**Comment by Asymtode712** [comment]
can you please send me a snippet of it

**Comment by Durgesh-Vaigandla** [comment]
see it's not enabled

image

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla ok just wait

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla Have you closed this??

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla I had committed some updations to the file

**Comment by Asymtode712** [comment]
should i make another pr?

**Comment by Durgesh-Vaigandla** [comment]
@Asymtode712 Just wait some time our backend team said that we'll fix this. So please wait I'll intimate you after fixing.

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla Do ping me as my other PRs are also on hold and i would have to make changes in them accordingly

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla please add 'leve1' and 'gssoc' labels to this PR

**Pull request merged**
