### PR TITLE
animations added

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
Aniamations added using AOS.js
issue #20 solved

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125277258/ca1cadc6-f361-4556-96e7-96c1929e79d1

### CODE REVIEW

**Comment by CSEdgeOff** [comment]
@RamakrushnaBiswal Kindly Attach the mobile view.

**Comment by RamakrushnaBiswal** [comment]
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/125277258/e3e930ff-423f-4d3b-93fa-e4c9225c0215

@CSEdgeOff sir

**Comment by CSEdgeOff** [comment]
@RamakrushnaBiswal There are some issues in the Mobile view could you solve it.? for the internship section and contact section i seem

**Comment by RamakrushnaBiswal** [comment]
sir actually the website is not responsive properly.like the icons .
some margins in the top

**Comment by CSEdgeOff** [comment]
@RamakrushnaBiswal Yes we want it if you do I'll make a new issue on it and assign to you and now I'm closing this PR

**Comment by CSEdgeOff** [comment]
@RamakrushnaBiswal Work on #10

**Pull request merged**
