### PR TITLE
Create close-old-pr.yml

### LINKED ISSUE #227: [Feature] Workflow for closing Old PRs
### Description

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

@Dplease assign me this issue under gssoc'24

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Asymtode712**
## Related Issue
Fixes #227 

## Description
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla please review this PR and merge it if it is good to go

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla can you please add 'gssoc' and the relevant level labels

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla can you please add the 'gssoc' and level labels

**Comment by Durgesh-Vaigandla** [comment]
PR merge comments are not working well Try to fix

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla It is still happening because of lack of 'repo' permission to the GITHUB_TOKEN, its solution is to create a PAT(classic) with 'repo' permission and assign it to a new environment secret in your repo by the name GITHUB_TOKEN

**Comment by Asymtode712** [comment]
**Step 1: Create a Personal Access Token (PAT) with repo Permission**


**1. Navigate to Settings:**

 - Click on your profile picture in the upper-right corner of the page.
 - Select "Settings" from the dropdown menu.

**2. Go to Developer Settings:**

- In the left sidebar, scroll down and click on "Developer settings."

**3. Create a New Token:**

- Click on "Personal access tokens" in the left sidebar.
- Click on the "Generate new token" button.

**4. Configure the Token:**

- Token Description: Enter a descriptive name for the token (e.g., Repo Access Token).
- Expiration: Set no expiration.
- Select Scopes: Check the box next to repo to grant full control of private repositories.

**5. Generate Token:**

- Scroll down and click on the "Generate token" button.
- Important: Copy the token to a secure location. You will not be able to see it again once you navigate away from the page.
<br>

**Step 2: Assign the Token to GITHUB_TOKEN Environment Variable**

**1. Navigate to Your Repository:**

- Go to your repository on GitHub.
- Click on the "Settings" tab.

**2. Go to Secrets:**

- In the left sidebar, click on "Secrets and variables" and then "Actions".

**3. Create a New Secret:**

- Click on the "New repository secret" button.
- Name: Enter GITHUB_TOKEN.
- Value: Paste your generated token.
- Click on the "Add secret" button.

**Comment by Asymtode712** [comment]
@Durgesh-Vaigandla please add 'leve1' and 'gssoc' labels to this PR

**Pull request merged**
