### PR TITLE
Fix Issue No #19: [ENHANCEMENT] Dark Mode

### PR DESCRIPTION
**Pull request by chaitanyarora**

### CODE REVIEW

**Comment by chaitanyarora** [comment]
#19

**Comment by chaitanyarora** [comment]
#140

**Comment by chaitanyarora** [comment]
#19

**Comment by CSEdgeOff** [comment]
## @chaitanyarora Where are the output.?

**Comment by chaitanyarora** [comment]
> ## @chaitanyarora Where are the output.?

Should I attach the screenshots as well sir?

**Comment by chaitanyarora** [comment]
Screenshot 2024-05-13 161629
Screenshot 2024-05-13 161538

**Comment by chaitanyarora** [comment]
@CSEdgeOff sir any update?

**Pull request closed without merging**
