### PR TITLE
 Add News Letter Button in CSEdge Learn

### PR DESCRIPTION
**Pull request by Gokilp**
## Related Issue
 #398 add a new's letter 

## Description
add a new's letter

screenshot 

image

### CODE REVIEW

**Comment by Gokilp** [comment]
please review my pr @CSEdgeOff

**Comment by CSEdgeOff** [comment]
@Gokilp Could you fix it or not ?
We already mentioned to use the code which we've provided in the issue template.

**Comment by Gokilp** [comment]
- Ok I will work on it

**Comment by Gokilp** [comment]
https://github.com/CSEdgeOfficial/learn.csedge.courses/pull/414

**Comment by Gokilp** [comment]
> #414
> 
> kindy please review my pr Im made UI part you will merge the pr It useful to me work the issue
> 
> Kindly please please check out it @CSEdgeOff

**Pull request closed without merging**
