### PR TITLE
added a codesnippet in an article

### PR DESCRIPTION
**Pull request by DEV-Soumya-Ranjan-Swain**
## Description

This pull request addresses issue #3 by implementing code snippet functionality in the new article "JavaScript Basics" under the JavaScript topic. 
you can check that by going to posts/javascript/javascript-basics.html.

image
### Changes Made:
- added a code snippet display component to enhance readability and functionality.
- created a new topic named javascript
- added a new article named javascript basics

### CODE REVIEW

**Comment by CSEdgeOff** [comment]
@DEV-Soumya-Ranjan-Swain Make some changes in your PR 
In the posts folder write a basic article on anything with similar structure which having existing ones
Try to implement your code snippet in that article.

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
could you elaborate a bit more, I am not getting what do u mean by similar structure which having existing ones

**Comment by CSEdgeOff** [comment]
@DEV-Soumya-Ranjan-Swain In the Posts Folder Write a New Article[Choose any Basic level of programming Task]
Use your code snippet functionality in that article 
Maintain the structure of the article as remaining articles.

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
can i choose java and write how to run their first hello world program

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
image

i have created a new article with a code snippet, by keeping the rest of the things as it is, you can merge it now

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
hey can you check my new commits

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
hey i have done it already, can you review and merge

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
it's been more than 2 days, can you review and merge it

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
can you review and merge it

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
it's been 2 weeks, why are you not reviewing it

**Comment by CSEdgeOff** [comment]
@DEV-Soumya-Ranjan-Swain  Sorry for the Delay in the PR Merging 
just add a Mobile view for a copy of Document here in the GitHub 
incase any updates needed I'll inform either we'll merge it

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
hey could you review and merge it

**Pull request merged**
