### PR TITLE
homepage revamp

### LINKED ISSUE #285: [Style] Homepage cards revamp
### What's the style idea?

We need to utilize the rest of space on the screen which is taken by
Screenshot 2024-05-24 at 11 02 43 AM

we can utilize the space below it so that the cards can show up to three instead of two which will also increase its attractiveness.

Screenshot 2024-05-24 at 11 01 19 AM

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/.github/CONTRIBUTING.md) of this project.
- [X] I am a GSSoC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Ratangulati**
## Related Issue
I have updated the homepage and made it look more clean.
Fixes #285 

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116749593/44127a54-96d7-43d8-a52d-34f9dba2f298

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Ratangulati** [comment]
@CSEdgeOff Please review the code.
Thankyou

**Comment by CSEdgeOff** [comment]
@Ratangulati Could you fix the nav bar ASAP

**Comment by Ratangulati** [comment]
> @Ratangulati Could you fix the nav bar ASAP
Do you want me to fix the scroll issue?

**Comment by Ratangulati** [comment]
Corrected the navbar rolling problem.
@CSEdgeOff

**Comment by Ratangulati** [comment]
Corrected the navbar scrolling problem.
@CSEdgeOff

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116749593/26364c64-88bf-4853-8cdb-9987f7572f6c

**Pull request closed without merging**
