### PR TITLE
Made Navbar Sticky

### PR DESCRIPTION
**Pull request by jency1**
## Related Issue
#463 Solved - Made Navbar Sticky

## Description
 Made Navbar Sticky which was not sticky before

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jency1** [comment]
@CSEdgeOff Please review and merge this PR.

**Comment by jency1** [comment]
@CSEdgeOff Please review and merge this PR.

I have solved the issue #463 which was assigned by you.

**Comment by jency1** [comment]
@CSEdgeOff Please review and merge this PR.

**Comment by jency1** [comment]
@CSEdgeOff Please review and merge this PR.

**Comment by jency1** [comment]
@Durgesh-Vaigandla  @CSEdgeOff Please review and merge this PR. 

I have solved the issue which was assigned by you.

**Comment by jency1** [comment]
@CSEdgeOff  Please merge this PR

**Comment by jency1** [comment]
@Durgesh-Vaigandla @CSEdgeOff Please review and merge this PR.

I have solved the issue which was assigned by you.

**Comment by jency1** [comment]
@Durgesh-Vaigandla @CSEdgeOff Please review and merge this PR.

I have solved the issue which was assigned by you.

**Comment by jency1** [comment]
@Durgesh-Vaigandla @CSEdgeOff Please review and merge this PR.

I have solved the issue which was assigned by you.

**Comment by jency1** [comment]
@Durgesh-Vaigandla @CSEdgeOff Please review and merge this PR.

I have solved the issue which was assigned by you. It's been already a month since I had solved this issue.

**Comment by jency1** [comment]
@Durgesh-Vaigandla @CSEdgeOff Please review and merge this PR as soon as possible.

I have solved all the issues which was assigned by you.

**Comment by jency1** [comment]
@sanjay-kv  Please merge this PR as soon as possible.

**Comment by sanjay-kv** [comment]
Stop spamming and read my newsletter

**Comment by jency1** [comment]
> Stop spamming and read my newsletter

@sanjay-kv Sir I am not spamming, I have raised this  PR since 2 months and the project admin is not merging this. I have mentioned this PR in unmerged PR also. 

Sorry for this inconvenience. Do consider this PR in unmerged PR's. 

Thank you.

**Comment by sanjay-kv** [comment]
image

Read the mail send last night, read discord discussion. You are tagging me everywhere which I can't merge on other people repo.

**Comment by jency1** [comment]
@sanjay-kv Ok sir I was not aware about it. As this is my first open source, I am facing some difficulties that's why.

I have raised this PR on the specified PR. Do check it. 

Sorry for this inconvenience.

**Pull request closed without merging**
