### PR TITLE
Improved UI of Internship Section

### PR DESCRIPTION
**Pull request by GarimaSingh0109**
This pull request proposes improvements to the UI of the internship section of the website using CSS. The changes aim to enhance responsiveness, readability, and overall user experience.
**Testing**: Manually tested the changes on various screen sizes and devices to ensure responsiveness.
Referenced the existing CSS code for the internship section while making changes.
Maintained a consistent coding style throughout the implementation.

Please review the implemented changes and provide feedback. I welcome suggestions for further improvement.
Thank you!
Garima Singh
cseedge_before
csedge_after

### CODE REVIEW

**Comment by CSEdgeOff** [comment]
@GarimaSingh0109 It seems too big decrease the card size make 3 cards inline so that it would looks better

**Comment by GarimaSingh0109** [comment]
ok working on it

**Comment by GarimaSingh0109** [comment]
I have made the required changes. Please review the implemented changes and provide feedback.
cseedge_before
csedge_after

**Comment by Lelin07** [comment]
@GarimaSingh0109 That looks good. It seems like the maintainers are ignorant

**Comment by GarimaSingh0109** [comment]
I too think so, thus I am closing the request. As I m neither getting any response or feedback.

**Pull request closed without merging**
