### PR TITLE
Made site responsive

### LINKED ISSUE #392: BUG: Make site responsive
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The home page is not responsive enough. It has got the horizontal scroll in other versions. Kindly assign me the issue under gssoc'24.
Screenshot 2024-06-02 183022

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by pankhuri92**
## Related Issue
The site wasn't responsive in versions from laptop-1024px
Fix #392

## Description
-The images were bigger than needed and moving out of screen. I reduced their scaling.
-The text size were larger than needed making it shabby. Adjusted the size.
-I changed the paddings to adequately distribute space.
-The buttons in internship were running out of the box. I adjusted the internship boxes to accommodate all the content.
-Adjusted the contact form & FAQ size and space
-Other minimal changes to finish off.

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/138357063/749aacce-e7db-4185-8850-88f0e344a9cc

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.

### CODE REVIEW

**Review by CSEdgeOff — CHANGES_REQUESTED** [review]
Fix the Footer Copy the footer from the home.html file

**Comment by pankhuri92** [comment]
@CSEdgeOff, thank you for reviewing. Just to clarify the requested change - you mean to make it less congested? I'll work on the spacing then.
Screenshot 2024-06-06 181307

**Comment by Durgesh-Vaigandla** [comment]
[checkout this page](https://learn.csedge.courses/home.html)

**Comment by pankhuri92** [comment]
@CSEdgeOff  I have made the required changes. I hope that suffices.

**Comment by pankhuri92** [comment]
Hi @CSEdgeOff & @Durgesh-Vaigandla , I have made changes as requested and rest all seems to work fine. Could you please review my pr and let me know if any further improvement is needed?

**Comment by pankhuri92** [comment]
\assign

**Comment by CSEdgeOff** [comment]
@pankhuri92 Update your PR so that We can be able to merge getting conflicts with your PR

**Comment by pankhuri92** [comment]
> @pankhuri92 Update your PR so that We can be able to merge getting conflicts with your PR

I have now resolved the conflicts. Please do let me know for further changes.

**Comment by pankhuri92** [comment]
Kindly merge the pr if no further requisites are there.

**Comment by pankhuri92** [comment]
@CSEdgeOff, kindly merge my pr. It's been over a month.

**Pull request closed without merging**
