### PR TITLE
Resolved file not found for freeContent

### PR DESCRIPTION
**Pull request by P-lavanya16**

### CODE REVIEW

**Comment by Durgesh-Vaigandla** [comment]
@P-lavanya16 Required more info

**Comment by P-lavanya16** [comment]
I have added link ref which is in other folder

**Comment by Durgesh-Vaigandla** [comment]
@P-lavanya16 It exists 

Navigate to folder CSEdge.courses
You'll find Resources.html files

**Comment by P-lavanya16** [comment]
Yes!in href it's added only for file name resources.html but ii's in a
folder .Hence href should be in folder/filename

**Comment by Durgesh-Vaigandla** [comment]
@P-lavanya16 yes I agree with it but the home.html is a file which the contributors using for testing because the main file is in the folder itself in the name of index.html

**Comment by P-lavanya16** [comment]
Ok, thanks for the clarification.

**Pull request closed without merging**
