### PR TITLE
Technical Content - How to Use Github

### PR DESCRIPTION
**Pull request by vaishali-sharma-20**
## Related Issue
Technical Content - How to Use Github
Issue/Task no- #303 

## Description
Created Page which guides you about how to use Github.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by vaishali-sharma-20 — COMMENTED** [review]
I uploaded the wrong file before, but I have corrected it. If there are still any issues or if I have uploaded the wrong content, please let me know.

**Review by Durgesh-Vaigandla — CHANGES_REQUESTED** [review]
Add some Images to for the clear reference.

**Comment by Durgesh-Vaigandla** [comment]
@vaishali-sharma-20 What's the reason behind of making changes in the home.css file?

**Comment by vaishali-sharma-20** [comment]
@Durgesh-Vaigandla  apologize for the recent modifications to the home.css file. I believe these changes were made in error. I kindly request that you review the code again.

**Review by Durgesh-Vaigandla — APPROVED** [review]

**Pull request merged**
