### PR TITLE
Changed Footer

### PR DESCRIPTION
**Pull request by CodeXsubham**
Changed Footer -

**BEFORE**
Screenshot 2024-06-04 174624

**AFTER**
image

### CODE REVIEW

**Comment by CodeXsubham** [comment]
@CSEdgeOff please merge it

**Comment by CSEdgeOff** [comment]
#401

**Comment by CSEdgeOff** [comment]
@CodeXsubham Fix the mobile view

**Comment by CodeXsubham** [comment]
@CSEdgeOff I'll Try im not that gud in mobile view

**Pull request merged**
