### PR TITLE
Added subscribe to newsletter

### LINKED ISSUE #472: [Feature] : Add subscribe to NewsLetter
### Description

Adding subscribe to news letter

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Related Issue
Added subscribe to newsletter

## Description
Added subscribe to newsletter

closes #472 

## Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x ] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff   I have added a new feature please check it and review it soon so that i can work on the another issues in your repo

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff  I have made the changes as you said 

are there any changes should i made tell me so that i can work on them

**Comment by Saipradyumnagoud** [comment]
image


This how it looks

**Comment by Saipradyumnagoud** [comment]
image

i have made the changes @CSEdgeOff

**Comment by CSEdgeOff** [comment]
#398

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff  why the updates are not visible in the website?

**Pull request merged**
