### PR TITLE
feat/preloader added

### PR DESCRIPTION
**Pull request by drick-infinity**
## Related Issue
#299 Preloader got cseesdge

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by drick-infinity** [comment]
above pr
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116994649/361eb113-9b72-4de6-ab4c-fafb4aa76d00

**Comment by CSEdgeOff** [comment]
@drick-infinity Need a pre view of pre loader

**Comment by drick-infinity** [comment]
https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116994649/364561a4-b38e-445e-ae33-d8c8e27efbff

on refreshing the website

**Comment by drick-infinity** [comment]
i added the functionality on refershing the page

**Comment by drick-infinity** [comment]
send the preloader of pr #390

https://github.com/CSEdgeOfficial/learn.csedge.courses/assets/116994649/acf05fdc-1e99-473a-a1cd-969838ca5e07

**Comment by CSEdgeOff** [comment]
#381 Already we detailed how we need a Pre loader

Need a Custom pre loader
which represents the company Logo and Name with little animations
the pre loader need to be clean not fancy.

**Pull request closed without merging**
