### PR TITLE
Added logo in the Blog page

### PR DESCRIPTION
**Pull request by SadafKausar2025**

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
please assign this issue to me #51

**Comment by CSEdgeOff** [comment]
@SadafKausar2025 Make the changes in all pages also.

**Comment by SadafKausar2025** [comment]
yes I tried but i didn't get the home page code

**Comment by SadafKausar2025** [comment]
only the blog page code is visible in index.html. but where is the other page can you please refer me?

**Comment by CSEdgeOff** [comment]
@SadafKausar2025 This project is all about Blog page only not the main page.

**Comment by SadafKausar2025** [comment]
soo how can i make changes in all pages?

**Comment by Durgesh-Vaigandla** [comment]
@Princegupta101 THE CODE FILE GO TO POSTS DIRECTORY THEIR YOU CAN FIND REMAINING PAGES

**Comment by SadafKausar2025** [comment]
No , i didn't find other pages in post directory

**Comment by CSEdgeOff** [comment]
@SadafKausar2025 
https://learn.csedge.courses/posts/github/how-to-create-github-account.html
https://learn.csedge.courses/posts/linkedin/creating-professional-linkedin-account.html

like more are there

**Pull request merged**
