### PR TITLE
Added how to host websites using netlify

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Related Issue
Added how to host websites using netlify
## Description
Added how to host websites using netlify

## Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by CSEdgeOff — CHANGES_REQUESTED** [review]
Need to add at least one Cover Image 
and revert changes in the Index.html because i already inform about changing the home page dynamically it will effects.

**Comment by Saipradyumnagoud** [comment]
> e Index.html because i already inform about changing the home page dyn

okay

**Review by Saipradyumnagoud — COMMENTED** [review]
Made the changes

**Review by Saipradyumnagoud — COMMENTED** [review]
made the changes

**Pull request merged**
