### PR TITLE
Adding Hover effects for the blog cards

### LINKED ISSUE #476: [Feature] : Hover effect for blogs
### Description

Adding a hover effects for the card bodies of blogs

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I am a GSSoC'24 contributor.
- [X] I want to work on this issue.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/CSEdgeOfficial/learn.csedge.courses/blob/main/CODE_OF_CONDUCT.md)".

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Related Issue
Adding Hover effects for the blog cards

## Description
Adding Hover effects for the blog cards
closes #476 
## Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x ] I have performed a self-review of my code
- [x ] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@CSEdgeOff please review the pull request

**Comment by Durgesh-Vaigandla** [comment]
@Saipradyumnagoud Can't do the merge now we're working on a complete re-structuring using dynamic display after 20th i can be able to communicate about this PR if the changes is still need in the PR we'll inform you.

Thanks for the Contributions
Keep Contributing..!

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud Can't do the merge now we're working on a complete re-structuring using dynamic display after 20th i can be able to communicate about this PR if the changes is still need in the PR we'll inform you.
> 
> Thanks for the Contributions Keep Contributing..!

Okay

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud Can't do the merge now we're working on a complete re-structuring using dynamic display after 20th i can be able to communicate about this PR if the changes is still need in the PR we'll inform you.
> 
> Thanks for the Contributions Keep Contributing..!

is the feature needed or can i close and work on another issues

**Comment by Durgesh-Vaigandla** [comment]
@Saipradyumnagoud at present we're putting in hold after 20th we need to look into that.
Before that I can't assure you.

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud at present we're putting in hold after 20th we need to look into that. Before that I can't assure you.

Are you changing whole user interface?

**Comment by Durgesh-Vaigandla** [comment]
@Saipradyumnagoud No the UI will be same the data will be displayed dynamically using backend

**Comment by Saipradyumnagoud** [comment]
> @Saipradyumnagoud No the UI will be same the data will be displayed dynamically using backend

ohh oky but there are two websites in a single website

**Comment by Saipradyumnagoud** [comment]
@Durgesh-Vaigandla can i get your discord id please?

**Comment by Durgesh-Vaigandla** [comment]
@Saipradyumnagoud durgesh_014

**Pull request closed without merging**
