### PR TITLE
Update home.css

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
Enhancing the Why CSEdge Internship section of the website

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
Why_Internship_SS

**Comment by Aditi22Bansal** [comment]
image

**Comment by CSEdgeOff** [comment]
@Aditi22Bansal What changed?

**Comment by Aditi22Bansal** [comment]
Done the changes 
Here it now how it looks
image

**Comment by Aditi22Bansal** [comment]
please check the above
Thanks

**Comment by CSEdgeOff** [comment]
Not clean

**Pull request closed without merging**
