### PR TITLE
Added Mode Toggler

### PR DESCRIPTION
**Pull request by VijaySamant4368**
## Related Issue
#560

## Description
Made the mode toggler with SVG images that changes based on the mode.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Uploading Screen Recording 2024-07-19 201325.mp4…

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
This pr is under GSSoC 2024. Please label it with appropriate labels.

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
@CSEdgeOff please review and merge this pr

**Comment by Durgesh-Vaigandla** [comment]
@VijaySamant4368 Add the screenshots of the outputs in different views

**Comment by VijaySamant4368** [comment]
After that small change, the Screenshots would be as follows:

At full screen
image

Width 1500px
image

Width 1000px
image

Width 500px
image

Width 300px
image

Although making it responsive for even smaller screen width is unnecessary, I can make it responsive, but I would have to change the other parts of the source-code.

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla, please kindly check.

**Comment by Durgesh-Vaigandla** [comment]
@VijaySamant4368 in mobile view incorporate the button inside the navbar I mean if the nav is open the button would display

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla, do you mean that I have to add the Toggle-Button in the drop down menu?
"If the user press the three lines(hamburger) button, then only the Toggle Mode should show" Is this what you mean?

**Comment by Durgesh-Vaigandla** [comment]
@VijaySamant4368 yeah exactly

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla it may take some time.

**Comment by VijaySamant4368** [comment]
Should I make it such that it is outside till the width is say 500px, but if it is less than that, it goes inside.
As the nav-bar would have a lot of empty space.
@Durgesh-Vaigandla

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla will these suffice?

For width less than 1100px, it is still same

The nav-Bar
image

Inside Hamburger
image
Pressing the 'Toggle Mode' toggles the mode and closes the hamburger.

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla please label this as GSSoC Level 3

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla does these changes look good, or is there any other specification that I should do?

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla @CSEdgeOff please checkout this pr

**Comment by VijaySamant4368** [comment]
@Durgesh-Vaigandla @CSEdgeOff  please kindly checkout this pr

**Pull request closed without merging**
